version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: pizzaria
      POSTGRES_PASSWORD: pizzaria
      POSTGRES_DB: pizzaria
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
